### ISSUE TITLE
Remote debug - adb connect

### ISSUE THREAD

**Issue by joaogbcravo** [agoda-com/android-farm#4]
Hey! Great work! I managed to put almost everything working. 
Now I'm with an issue that not sure is a problem on my side or a missing feature of the android-farm.

On STF, on the "Remote debug" box appears the stf-provider pod IP address
![image](https://user-images.githubusercontent.com/6697174/46813391-e49b0600-cd76-11e8-8689-416e9d039e9e.png)
this of course is not accessible outside the kubernetes cluster.

Are you able to use adb connect in any other way? I'm missing something? 

Thanks

**Comment by neofreko** [comment]
You can use `kubectl port-forward pods/<pod-name> 15005:15005`. Then you can `adb connect 127.0.0.1:15005`.
It's manual but I can't think of any other way.

**Comment by joaogbcravo** [comment]
Hey! Thanks for the reply...
well.. that would be "ugly" in terms of management... I mean every time that somehow the pod dies we have to redo the forwarding... 

I guess I will keep everything in kubernetes except the real-provider... not sure if is better, but at least appears to be more stable.
